# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#
# - check app health
# - build docker image
# - publish docker image on dockerhub

# stage definition
stages:
    - audit
    - build
    - publish

# -----------
# build
# -----------

docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  script:
    - docker build --pull -t "tellebma/$CI_PROJECT_NAME:latest" .
    
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

# -----------
# publish
# -----------

docker-push:
  # Use the official docker image.
  image: docker:latest
  stage: publish
  before_script:
    # connect to dockerhub. ids on one/CICD var
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
  script:
    # publish docker image on docker hub.
    - docker push "tellebma/$CI_PROJECT_NAME:latest"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile


# -----------
# audit stage
# -----------

lint:
  image: node:18
  stage: audit
  script:
    # lint project.
    - yarn && yarn lint

prettier:
  image: node:18
  stage: audit
  script:
    # prettier project.
    - yarn && yarn prettier:check
